[package]
name = "toy_chain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
blake3 = { version = "1.3.0" }
chrono = { version = "0.4.19", features = ["serde"] }
